import "../_styles/globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

const space_grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={space_grotesk.className}>
        <div className="relative flex flex-col gap-section bg-primary-black text-white px-[16px] md:gap-0 md:px-0 lg:items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
